[package]
name = "email-wallet-utils"
version = "0.1.0"
authors = ["Sora Suegami"]
license = "MIT"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
# halo2-regex = { git = "https://github.com/zkemail/halo2-regex.git", version = "0.1.0" }
zk-regex-apis = { version = "0.1.0", git = "https://github.com/zkemail/zk-regex.git", branch = "feat/integrate_halo2_regex" }
fancy-regex = "0.11.0"
hex = "0.4.3"
tokio = { version = "1.16", features = [
    "net",
    "io-util",
    "time",
    "rt-multi-thread",
    "macros",
] }
serde_regex = "1.1.0"
# mail-auth = { git = "https://github.com/Divide-By-0/mail-auth.git", version = "0.3.0", branch = "main" }
# trust-dns-resolver = "0.23.0"
anyhow = "1.0.75"
once_cell = "1.18.0"
poseidon-rs = { git = "https://github.com/SoraSuegami/poseidon-rs.git", version = "0.0.10", branch = "master" }
halo2curves = { version = "0.4.0", git = "https://github.com/privacy-scaling-explorations/halo2curves.git" }
num-bigint = "0.4.4"
base64 = "0.21.4"
rsa = { version = "0.6.1", features = ["serde"] }
num-traits = "0.2.15"
cfdkim = { version = "0.3.0", git = "https://github.com/SoraSuegami/dkim.git" }
slog = "2.7.0"


[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6", "channel-api", "promise-api"]
